"""empty message

Revision ID: 15bda11cf830
Revises: 
Create Date: 2020-01-11 16:41:08.258131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bda11cf830'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_title', sa.String(length=100), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('contents', sa.Text(), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('blog_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author')
    )
    op.create_index(op.f('ix_blog_blog_title'), 'blog', ['blog_title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_blog_title'), table_name='blog')
    op.drop_table('blog')
    # ### end Alembic commands ###
