"""empty message

Revision ID: 25ce8bab3920
Revises: 73062a25eaca
Create Date: 2020-02-21 17:52:02.854310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ce8bab3920'
down_revision = '73062a25eaca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip', sa.Column('today_time', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip', 'today_time')
    # ### end Alembic commands ###
