"""empty message

Revision ID: 73062a25eaca
Revises: b415d834f421
Create Date: 2020-02-21 17:49:42.729654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73062a25eaca'
down_revision = 'b415d834f421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sum_', sa.Integer(), nullable=True),
    sa.Column('last_seven_days', sa.String(length=80), nullable=True),
    sa.Column('today_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip')
    # ### end Alembic commands ###
