"""empty message

Revision ID: b415d834f421
Revises: 605ac8696b4f
Create Date: 2020-02-13 15:33:44.952566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b415d834f421'
down_revision = '605ac8696b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('preview', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'preview')
    # ### end Alembic commands ###
