"""empty message

Revision ID: d70320df8b8e
Revises: 703cfa46cc60
Create Date: 2020-03-09 13:27:05.551737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70320df8b8e'
down_revision = '703cfa46cc60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('is_show', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'is_show')
    # ### end Alembic commands ###
